'use client';

import { ExternalLink, ImageIcon, MapPin, Pencil, Trash2 } from 'lucide-react';
import type { GeneratedHospitalityDemo } from '@/src/tourism-theme/src/generated/types';

const value = (input: unknown) => typeof input === 'string' ? input : input && typeof input === 'object' ? String((input as Record<string, unknown>).ro || (input as Record<string, unknown>).en || '') : '';

export default function HospitalityAdminOverview({ demos, onEdit, onDelete, deletingSlug }: { demos: GeneratedHospitalityDemo[]; onEdit: (demo: GeneratedHospitalityDemo) => void; onDelete: (demo: GeneratedHospitalityDemo) => void; deletingSlug: string }) {
  if (!demos.length) return null;
  return <section className="mb-7 overflow-hidden rounded-[2rem] border border-white/10 bg-gradient-to-br from-emerald-500/[.08] via-white/[.035] to-blue-500/[.05] p-6 sm:p-8">
    <div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-emerald-400">Live portfolio</p><h2 className="mt-2 text-2xl font-bold text-white">Active hospitality demos</h2><p className="mt-2 text-sm text-slate-400">Visual overview of every published property.</p></div><div className="rounded-2xl border border-emerald-400/20 bg-emerald-400/10 px-5 py-3"><b className="text-2xl text-white">{demos.length}</b><span className="ml-2 text-xs uppercase tracking-widest text-emerald-300">active</span></div></div>
    <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{demos.map(item => { const cover = item.heroImage || item.images?.[0]; return <article key={item.slug} className="group overflow-hidden rounded-3xl border border-white/10 bg-slate-950/80 shadow-xl shadow-black/20 transition hover:-translate-y-1 hover:border-emerald-400/30">
      <div className="relative aspect-[16/10] overflow-hidden bg-slate-900">{cover ? <img src={cover} alt={value(item.property.name)} referrerPolicy="no-referrer" className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/> : <div className="grid h-full place-items-center"><ImageIcon className="h-10 w-10 text-slate-700"/></div>}<div className="absolute inset-0 bg-gradient-to-t from-slate-950 via-transparent to-transparent"/><span className="absolute left-4 top-4 rounded-full border border-emerald-300/20 bg-emerald-950/80 px-3 py-1 text-[10px] font-black uppercase tracking-widest text-emerald-300">Published</span><div className="absolute inset-x-4 bottom-4"><h3 className="truncate text-xl font-bold text-white">{value(item.property.name) || item.slug}</h3><p className="mt-1 flex items-center gap-1 text-xs text-slate-300"><MapPin className="h-3.5 w-3.5"/>{item.property.cityRegion || item.property.address || 'Location not set'}</p></div></div>
      <div className="p-4"><div className="grid grid-cols-3 gap-2 text-center"><div className="rounded-xl bg-white/[.04] p-2"><b className="block text-white">{item.images?.length || 0}</b><span className="text-[10px] text-slate-500">Photos</span></div><div className="rounded-xl bg-white/[.04] p-2"><b className="block text-white">{item.rooms?.length || 0}</b><span className="text-[10px] text-slate-500">Rooms</span></div><div className="rounded-xl bg-white/[.04] p-2"><b className="block text-white">{item.attractions?.length || 0}</b><span className="text-[10px] text-slate-500">Attractions</span></div></div><div className="mt-4 flex gap-2"><a href={`/demo/${item.slug}`} target="_blank" rel="noreferrer" className="flex flex-1 items-center justify-center gap-1.5 rounded-xl bg-emerald-600 px-3 py-2.5 text-xs font-bold text-white hover:bg-emerald-500"><ExternalLink className="h-3.5 w-3.5"/>Open</a><button onClick={() => onEdit(item)} className="grid h-10 w-10 place-items-center rounded-xl border border-white/10 bg-white/5 hover:bg-white/10" title="Edit"><Pencil className="h-4 w-4"/></button><button disabled={deletingSlug === item.slug} onClick={() => onDelete(item)} className="grid h-10 w-10 place-items-center rounded-xl border border-red-400/20 bg-red-400/10 text-red-300 hover:bg-red-400/20 disabled:opacity-40" title="Delete"><Trash2 className="h-4 w-4"/></button></div></div>
    </article>; })}</div>
  </section>;
}
